### PR TITLE
php 5.4 changes...

### PR DESCRIPTION
**Pull request by sivad77**

### CODE REVIEW

**Comment by dhotson** [comment]
Hey sorry about the wait, I must've missed the notification on this one. My bad.

Newbie question: Is this change backwards compatible with 5.3? Does PHP 5.4 introduce breaking changes to the extension API?

**Comment by sivad77** [comment]
Ah, no worries...

I would assume this is not backwards compatible...That is an assumption...It has been so long since I looked at this.

I am onto NodeJS at work now....No more PHP for me....:D

Yes, PHP changed their APIs in 5.4 (from what I remember).

**Comment by dhotson** [comment]
Haha, yeah I've moved onto Node (and Ruby) now mostly too.
I'm still stuck with a few bits of PHP here and there. :-P

I'm still keen to advance the PHP webserver ecosystem with [kelpie](http://getkelpie.com/) but it's going to take a pretty massive effort to push ahead and get adoption. I'd like to get it adopted where I [work](http://99designs.com/). I got a prototype working that was ~10-15 times faster purely because it eliminated framework init time on every request. Pretty compelling to the business, but I'm a bit nervous about putting my (toy) web server into production. ;-)

It'd be great to get Symfony and other popular PHP frameworks working too...

Anyway, I'll keep you updated. Thanks so much for the contribution. Cheers!

**Comment by sivad77** [comment]
Sounds awesome! I am not sure how php is with garbage collection :(

I also write a lot of Node these days at work.

**Comment by dhotson** [comment]
Hey sorry, I'm only just getting back onto this now haha. Been a while. :)

**Pull request merged**
